# app/utils/labels.py
# Transparency label generator.
# No implementation — skeleton only.
#
# TODO (Milestone 5): Implement label generation.
#
# Design spec (from planning.md) — exact label variant texts:
#
# VARIANT 1 — High-Confidence AI (attribution: likely_ai, confidence >= 0.65):
#   "AI-Assisted Content
#    Our systems detected patterns consistent with AI-generated text (confidence: HIGH).
#    This label does not prevent you from reading or engaging with this work.
#    If you are the creator and believe this is incorrect, you can submit an appeal."
#
# VARIANT 2 — High-Confidence Human (attribution: likely_human, confidence <= 0.35):
#   "Human-Authored Content
#    Our systems found strong indicators that this work was written by a person (confidence: HIGH).
#    Enjoy the work knowing it reflects a human creative voice."
#
# VARIANT 3 — Uncertain (attribution: uncertain, confidence 0.36–0.64):
#   "Attribution Unclear
#    Our systems were unable to determine with confidence whether this content was written
#    by a person or generated by AI (confidence: LOW).
#    We encourage you to consider the context. If you are the creator and believe this
#    classification is wrong, you can submit an appeal."

LABEL_LIKELY_AI = (
    "AI-Assisted Content\n"
    "Our systems detected patterns consistent with AI-generated text (confidence: HIGH).\n"
    "This label does not prevent you from reading or engaging with this work.\n"
    "If you are the creator and believe this is incorrect, you can submit an appeal."
)

LABEL_LIKELY_HUMAN = (
    "Human-Authored Content\n"
    "Our systems found strong indicators that this work was written by a person (confidence: HIGH).\n"
    "Enjoy the work knowing it reflects a human creative voice."
)

LABEL_UNCERTAIN = (
    "Attribution Unclear\n"
    "Our systems were unable to determine with confidence whether this content was written "
    "by a person or generated by AI (confidence: LOW).\n"
    "We encourage you to consider the context. If you are the creator and believe this "
    "classification is wrong, you can submit an appeal."
)


def generate_label(attribution: str, confidence: float) -> str:
    """
    Return the appropriate transparency label text for the given attribution.

    Args:
        attribution: One of "likely_ai", "likely_human", "uncertain".
        confidence: Float 0.0–1.0 confidence score.

    Returns:
        Exact label text string (one of the three variants above).

    Raises:
        ValueError: If attribution is not a recognized value.
    """
    # TODO: implement
    # Map attribution to the exact label text constants above
    raise NotImplementedError("Label generation not yet implemented")
