# app/utils/labels.py
# Transparency label generator — three variants, texts are part of public contract.
# Label text also appears verbatim in README.md and planning.md.

from app.utils.confidence import ATTRIBUTION_LIKELY_AI, ATTRIBUTION_LIKELY_HUMAN

LABEL_LIKELY_AI = (
    "AI-Assisted Content\n"
    "Our systems detected patterns consistent with AI-generated text (confidence: HIGH).\n"
    "This label does not prevent you from reading or engaging with this work.\n"
    "If you are the creator and believe this is incorrect, you can submit an appeal."
)

LABEL_LIKELY_HUMAN = (
    "Human-Authored Content\n"
    "Our systems found strong indicators that this work was written by a person (confidence: HIGH).\n"
    "Enjoy the work knowing it reflects a human creative voice."
)

LABEL_UNCERTAIN = (
    "Attribution Unclear\n"
    "Our systems were unable to determine with confidence whether this content was written "
    "by a person or generated by AI (confidence: LOW).\n"
    "We encourage you to consider the context. If you are the creator and believe this "
    "classification is wrong, you can submit an appeal."
)

_LABEL_MAP = {
    ATTRIBUTION_LIKELY_AI: LABEL_LIKELY_AI,
    ATTRIBUTION_LIKELY_HUMAN: LABEL_LIKELY_HUMAN,
    "uncertain": LABEL_UNCERTAIN,
}


def generate_label(attribution: str, confidence: float) -> str:
    """
    Return the exact transparency label text for the given attribution.

    Args:
        attribution: One of "likely_ai", "likely_human", "uncertain".
        confidence: Float 0.0–1.0 (unused in dispatch but kept for signature parity).

    Returns:
        Exact label text string.

    Raises:
        ValueError: If attribution is not a recognized value.
    """
    label = _LABEL_MAP.get(attribution)
    if label is None:
        raise ValueError(f"Unknown attribution value: {attribution!r}")
    return label
