# app/signals/llm_signal.py
# Signal 1: LLM-based semantic classification using Groq.
#
# Blind spots: adversarially humanized AI text, heavily edited AI output,
# unusually formal human writing, styles underrepresented in training data.

import json
import os

from groq import Groq

_MODEL = "llama-3.3-70b-versatile"

_PROMPT = (
    "You are an AI content detection system. Analyze the following text and assess "
    "the probability that it was generated by an AI (rather than written by a human).\n\n"
    "Respond with ONLY valid JSON in this exact format: {\"ai_probability\": <float between 0.0 and 1.0>}\n\n"
    "Where 1.0 = certainly AI-generated and 0.0 = certainly human-written.\n\n"
    "Text to analyze:\n"
)

_PROMPT_IMAGE_DESCRIPTION = (
    "You are an AI content detection system. The following text is a description or caption "
    "for an image. Assess the probability that this description was generated by an AI "
    "(rather than written by a human).\n\n"
    "Respond with ONLY valid JSON in this exact format: {\"ai_probability\": <float between 0.0 and 1.0>}\n\n"
    "Where 1.0 = certainly AI-generated and 0.0 = certainly human-written.\n\n"
    "Image description to analyze:\n"
)

# Module-level singleton — initialized once on first real call.
# Tests inject a mock via the client= parameter instead of patching os.environ.
_client: Groq | None = None


def classify_with_llm(text: str, client=None, content_type: str = "text") -> float:
    global _client
    if client is None:
        if _client is None:
            _client = Groq(api_key=os.environ["GROQ_API_KEY"])
        client = _client

    prompt = _PROMPT_IMAGE_DESCRIPTION if content_type == "image_description" else _PROMPT

    response = client.chat.completions.create(
        model=_MODEL,
        messages=[{"role": "user", "content": prompt + text}],
        temperature=0.0,
        max_tokens=32,
    )
    raw = response.choices[0].message.content.strip()
    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"Groq returned unparseable response: {raw!r}") from exc
    return max(0.0, min(1.0, score))
