# app/signals/llm_signal.py
# Signal 1: LLM-based semantic classification using Groq.
#
# Blind spots: adversarially humanized AI text, heavily edited AI output,
# unusually formal human writing, styles underrepresented in training data.

import json
import os

from groq import Groq

_MODEL = "llama-3.3-70b-versatile"

_PROMPT = (
    "You are an AI content detection system. Analyze the following text and assess "
    "the probability that it was generated by an AI (rather than written by a human).\n\n"
    "Respond with ONLY valid JSON in this exact format: {\"ai_probability\": <float between 0.0 and 1.0>}\n\n"
    "Where 1.0 = certainly AI-generated and 0.0 = certainly human-written.\n\n"
    "Text to analyze:\n"
)


def classify_with_llm(text: str) -> float:
    """
    Call the Groq LLM to assess whether text is AI-generated.

    Args:
        text: The content to classify.

    Returns:
        Float 0.0–1.0 where 1.0 = highly likely AI-generated.

    Raises:
        ValueError: If the API response cannot be parsed.
        Exception: On API call failure.
    """
    client = Groq(api_key=os.environ["GROQ_API_KEY"])
    response = client.chat.completions.create(
        model=_MODEL,
        messages=[{"role": "user", "content": _PROMPT + text}],
        temperature=0.0,
        max_tokens=32,
    )
    raw = response.choices[0].message.content.strip()
    try:
        parsed = json.loads(raw)
        score = float(parsed["ai_probability"])
    except (json.JSONDecodeError, KeyError, TypeError, ValueError) as exc:
        raise ValueError(f"Groq returned unparseable response: {raw!r}") from exc
    return max(0.0, min(1.0, score))
